### ISSUE TITLE
npm2yarn save selected tab in `localStorage`

### ISSUE THREAD

**Issue by B2o5T** [the-guild-org/docs#1119]
https://guild-oss.slack.com/archives/CAY2119MX/p1686306294493689?thread_ts=1686305363.428799&cid=CAY2119MX

and show it by default

**Comment by ashutosh887** [comment]
@B2o5T Should I work on this?

**Comment by B2o5T** [comment]
Go with it

**Comment by ashutosh887** [comment]
@B2o5T Which tabs are we planning to save to localstorage?
Let's discuss

**Comment by B2o5T** [comment]
selected tab

**Comment by ashutosh887** [comment]
Thanks @B2o5T 
Will start working... Please assign

**Comment by B2o5T** [comment]
No assign, sorry
