### ISSUE TITLE
Search v2 improvements/bugs

### ISSUE THREAD

**Issue by charlypoly** [the-guild-org/docs#372]
- [ ] "no result" when loading glitch
- [ ] highlight color is missing opacity
- [ ] display "⌘ K" or "Ctrl K" in the search input
- [ ] overall better design
- [ ] fix sorting of results (@charlypoly)
- [ ] idea: add 1 record per "product" that rank first when searching for product name (ex: "Yoga" should display a result/card presenting Yoga, etc)
- [ ] Algolia Insights seems to be broken 🤔 (https://www.algolia.com/doc/ui-libraries/autocomplete/api-reference/autocomplete-plugin-algolia-insights/createAlgoliaInsightsPlugin/)
- [x] Remove top imports when extracting content 🐞  (https://github.com/the-guild-org/the-guild-docs/pull/658)

**Comment by charlypoly** [comment]
> `highlight color is missing opacity` I removed it's explicitly due installation of 1 package to change opacity in 1 place

@B2o5T yes but it was crucial UX wise because right now the highlight colors look very bad, for example on GraphQL Tools: 

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/1252066/167629861-14b82823-4e51-458f-9395-956469ac847f.png">

**Comment by B2o5T** [comment]
> yes but it was crucial UX wise because right now the highlight colors look very bad, for example on the GraphQL Tools website:

maybe instead of setting background as `accentColor` we should change text color of `accentColor` + fontWeight: bold?

**Comment by charlypoly** [comment]
> maybe instead of setting background as `accentColor` we should change text color of `accentColor` + fontWeight: bold?

I guess just text-color would do the job yes!
