### ISSUE TITLE
Bug: clicking a result in Algolia search doesn't redirect

### ISSUE THREAD

**Issue by gilgardosh** [the-guild-org/docs#523]
[reference](https://tortilla-hq.slack.com/archives/C0261Q2LJM7/p1666255266613289?thread_ts=1666251257.521909&cid=C0261Q2LJM7)

https://user-images.githubusercontent.com/56203151/196901094-18c24204-d584-4aa4-9062-7e93da2d6a30.mov

**Comment by dimaMachina** [comment]
https://github.com/the-guild-org/docs/issues/1484#issuecomment-2432428793
