### ISSUE TITLE
PackageCmd - whitespace

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/docs#588]
Selecting npm or pnpm adds whitespace between the tabs and the code.

![image](https://user-images.githubusercontent.com/14338007/200534441-f299f982-576d-44f5-b026-29e09c85eff5.png)

![image](https://user-images.githubusercontent.com/14338007/200534493-b9e0e461-4846-4531-894f-03853893c949.png)

![image](https://user-images.githubusercontent.com/14338007/200534539-06cd68df-be21-496d-94c5-17519765a7cf.png)

**Comment by B2o5T** [comment]
Danke mein Freund!
