### ISSUE TITLE
bug: edit this page button doesn't redirect to the correct url for readme in Envelop plugins pages

### ISSUE THREAD

**Issue by YassinEldeeb** [the-guild-org/docs#673]
So when clicking on the "Edit this page on Github" button on any of the pages for Envelop's plugins [this for example](https://the-guild.dev/graphql/envelop/plugins/use-apollo-server-errors#usage-example). it redirects to the MDX component responsible for importing the markdown for each plugin as oppose to the plugin's readme URL.

**Comment by dotansimha** [comment]
@YassinEldeeb I think this happens because of the lack of support for the dynamic pages?

**Comment by YassinEldeeb** [comment]
mmm... interesting. can you elaborate more? I don't have much context about how this's working

**Comment by dotansimha** [comment]
> mmm... interesting. can you please elaborate more? I don't have much context about how this's working

For all regular pages (md, mdx) in our websites, the path to the file when clicking on "Edit this page" is inferred from the MDX file (which is static).
For Envelop plugins pages, we have a "dynamic" page that is being filled by the fact that we implement `getStaticPaths`, you can find it here: 
https://github.com/n1ru4l/envelop/blob/main/website/src/pages/plugins/%5Bname%5D.mdx  and https://github.com/n1ru4l/envelop/blob/main/website/src/lib/plugin-get-static-props.ts#L7 

So when Next builds the pages, it uses `getStaticPaths` to generate the URLs. The `Edit this page` takes the NextJS route name by default (the static one). 

@B2o5T can refine my answer and correct me if I'm wrong

**Comment by YassinEldeeb** [comment]
ooh, now I get it. thanks for clarifying. that being said can't we add another field there to control the "Edit this page on Github" URL? https://github.com/n1ru4l/envelop/blob/main/website/src/lib/plugins.ts#L38 👀

**Comment by dotansimha** [comment]
> ooh, now I get it. thanks for clarifying. that being said can't we add another field there to control the "Edit this page on Github" URL? [n1ru4l/envelop@`main`/website/src/lib/plugins.ts#L38](https://github.com/n1ru4l/envelop/blob/main/website/src/lib/plugins.ts?rgh-link-date=2022-12-12T11%3A37%3A35Z#L38) 👀

I assume it is possible, probably just point to a specific file, something like that: 
```
editLink: false | string // false to disable, in case of an external link or unknown, and a string is to set the path to the GH file 
```

But we also need a way to pass this from `pluginsArr` to `getStaticPaths` and then all the way to the Edit component (@B2o5T is it even possible?)

**Comment by YassinEldeeb** [comment]
oh wait, you already have this field there https://github.com/n1ru4l/envelop/blob/main/website/src/lib/plugins.ts#L81, but why it's not working/being used

**Comment by YassinEldeeb** [comment]
oh, so it's a matter of how to pass these metadata this far?

**Comment by dotansimha** [comment]
I guess so. I think the edit button is coming from Nextra (see https://github.com/shuding/nextra/blob/73241b3fee58f0318e9349a5eb7650a7cd55a4e3/packages/nextra-theme-docs/src/constants.tsx#L33 ) and it's using `getGitEditUrl`. 
I guess we can override this in https://github.com/n1ru4l/envelop/blob/main/website/theme.config.tsx#L6 and have a custom `editLink.component` that uses custom behavior for the plugins pages of Envelop?

**Comment by B2o5T** [comment]
closed since was fixed for envelop
