### ISSUE TITLE
Upgrading to v4

### ISSUE THREAD

**Issue by vicary** [the-guild-org/docs#699]
Hi, I am upgrading from `@guild-docs/client` to `@theguild/components` in GQty.

I found the current version of `@theguild/components@4.4.4` requires React 18, but it's dependency `nextra-theme-docs@2.0.0-beta.43` wants React 16-17.

Which version of React shall I pick?

**Comment by dotansimha** [comment]
Hi @vicary 
We dropped the client/server packages a long time ago, in favor of a wrapper for Nextra and NextJS. 
You can find an example for a simple website here: https://github.com/Urigo/graphql-scalars/tree/master/website (check [next.config.mjs](https://github.com/Urigo/graphql-scalars/blob/master/website/next.config.mjs) and the deps under `package.json`)

**Comment by vicary** [comment]
@dotansimha Thanks for the reply, and sorry for giving irrelevant information here.

I am exactly in the middle of removing the dropped packages, my question is about an incompatibility between the React requirement between the package `@theguild/components@4.4.4` and one of it's own dependency `nextra-theme-docs@2.0.0-beta.43`.

For clarity, I am attaching the screenshot of both versions of React below:

| React 17                                                                                                                                                           | React 18                                                                                                                                                           |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| <img width="361" alt="Screenshot 2023-01-01 at 16 29 38" src="https://user-images.githubusercontent.com/85772/210165154-7f1f73c2-9222-4bf6-b940-ada944c489a8.png"> | <img width="486" alt="Screenshot 2023-01-01 at 16 31 17" src="https://user-images.githubusercontent.com/85772/210165156-4e0eaef7-4f1c-4937-906e-2dded403c036.png"> |

**Comment by dotansimha** [comment]
@B2o5T can you please take a look?

**Comment by B2o5T** [comment]
@vicary I'll suggest you use Nextra directly https://nextra.site/
