### ISSUE TITLE
file tree component

### ISSUE THREAD

**Issue by n1ru4l** [the-guild-org/docs#779]
<img width="856" alt="image" src="https://user-images.githubusercontent.com/14338007/215997465-20d3147f-114b-4db5-9b73-d89e4de684b8.png">

It would also be fire if it allowed me to show the file contents next to file tree 🤔

https://github.com/shuding/nextra/blob/main/docs/components/file-tree/index.tsx

**Comment by B2o5T** [comment]
https://github.com/shuding/nextra/pull/1467
